export const SET_REDIRECT_TO = "AUTH.SET_REDIRECT_TO";

export const LOGIN_REQUEST = "AUTH.LOGIN_REQUEST";
export const LOGIN_SUCCESS = "AUTH.LOGIN_SUCCESS";
export const LOGIN_FAILURE = "AUTH.LOGIN_FAILURE";

export const LOGIN_FACEBOOK_REQUEST = "AUTH.LOGIN_FACEBOOK_REQUEST";
export const LOGIN_FACEBOOK_SUCCESS = "AUTH.LOGIN_FACEBOOK_SUCCESS";
export const LOGIN_FACEBOOK_FAILURE = "AUTH.LOGIN_FACEBOOK_FAILURE";

export const LOGIN_GOOGLE_REQUEST = "AUTH.LOGIN_GOOGLE_REQUEST";
export const LOGIN_GOOGLE_SUCCESS = "AUTH.LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAILURE = "AUTH.LOGIN_GOOGLE_FAILURE";

export const VERIFY_EMAIL_REQUEST = "AUTH.VERIFY_EMAIL_REQUEST";
export const VERIFY_EMAIL_SUCCESS = "AUTH.VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILURE = "AUTH.VERIFY_EMAIL_FAILURE";
