export const GET_EMPLOYERS_REQUEST = "EMPLOYER.GET_EMPLOYERS_REQUEST"
export const GET_EMPLOYERS_SUCCESS = "EMPLOYER.GET_EMPLOYERS_SUCCESS"
export const GET_EMPLOYERS_FAILURE = "EMPLOYER.GET_ALL_EMPLOYERS_FAILURE"