export const SUBMIT_JOB_AD_REQUEST = "JOB.SUBMIT_JOB_AD_REQUEST";
export const SUBMIT_JOB_AD_SUCCESS = "JOB.SUBMIT_JOB_AD_SUCCESS";
export const SUBMIT_JOB_AD_FAILURE = "JOB.SUBMIT_JOB_AD_FAILURE";

export const SUBMIT_EMPLOYER_DETAILS_REQUEST = "JOB.SUBMIT_EMPLOYER_DETAILS_REQUEST"
export const SUBMIT_EMPLOYER_DETAILS_SUCCESS = "JOB.SUBMIT_EMPLOYER_DETAILS_SUCCESS"
export const SUBMIT_EMPLOYER_DETAILS_FAILURE = "JOB.SUBMIT_EMPLOYER_DETAILS_FAILURE"

export const GET_ALL_JOBS_REQUEST = "JOB.GET_ALL_JOBS_REQUEST"
export const GET_ALL_JOBS_SUCCESS = "JOB.GET_ALL_JOBS_SUCCESS"
export const GET_ALL_JOBS_FAILURE = "JOB.GET_ALL_JOBS_FAILURE"

export const GET_SINGLE_JOB_REQUEST = "JOB.GET_SINGLE_JOB_REQUEST"
export const GET_SINGLE_JOB_SUCCESS = "JOB.GET_SINGLE_JOB_SUCCESS"
export const GET_SINGLE_JOB_FAILURE = "JOB.GET_SINGLE_JOB_FAILURE"

export const SUBMIT_CV_TO_EMPLOYER_REQUEST = "JOB.SUBMIT_CV_TO_EMPLOYER_REQUEST"
export const SUBMIT_CV_TO_EMPLOYER_SUCCESS = "JOB.SUBMIT_CV_TO_EMPLOYER_SUCCESS"
export const SUBMIT_CV_TO_EMPLOYER_FAILURE = "JOB.SUBMIT_CV_TO_EMPLOYER_FAILURE"

export const GET_SINGLE_JOB_WITH_APPLICANTS_REQUEST ="JOB.GET_SINGLE_JOB_WITH_APPLICANTS_REQUEST"
export const GET_SINGLE_JOB_WITH_APPLICANTS_SUCCESS ="JOB.GET_SINGLE_JOB_WITH_APPLICANTS_SUCCESS"
export const GET_SINGLE_JOB_WITH_APPLICANTS_FAILURE ="JOB.GET_SINGLE_JOB_WITH_APPLICANTS_FAILURE"