export const SUBMIT_JOB_AD_REQUEST = "JOB.SUBMIT_JOB_AD_REQUEST";
export const SUBMIT_JOB_AD_SUCCESS = "JOB.SUBMIT_JOB_AD_SUCCESS";
export const SUBMIT_JOB_AD_FAILURE = "JOB.SUBMIT_JOB_AD_FAILURE";

export const SUBMIT_EMPLOYER_DETAILS_REQUEST = "JOB.SUBMIT_EMPLOYER_DETAILS_REQUEST"
export const SUBMIT_EMPLOYER_DETAILS_SUCCESS = "JOB.SUBMIT_EMPLOYER_DETAILS_SUCCESS"
export const SUBMIT_EMPLOYER_DETAILS_FAILURE = "JOB.SUBMIT_EMPLOYER_DETAILS_FAILURE"