export const REGISTER_REQUEST = "USER.REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USER.REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USER.REGISTER_FAILURE";

export const SUBMIT_CV_REQUEST = "USER.SUBMIT_CV_REQUEST";
export const SUBMIT_CV_SUCCESS = "USER.SUBMIT_CV_SUCCESS";
export const SUBMIT_CV_FAILURE = "USER.SUBMIT_CV_FAILURE";

export const GET_JOB_APPS_REQUEST = "USER.GET_JOB_APPS_REQUEST";
export const GET_JOB_APPS_SUCCESS = "USER.GET_JOB_APPS_SUCCESS";
export const GET_JOB_APPS_FAILURE = "USER.GET_JOB_APPS_FAILURE";
